title: Snapchat
description: A portfolio project demonstrating the application of algorithms and data structures in optimizing user interactions and content management on Snapchat, a popular multimedia messaging app.
show_downloads: false
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
