title: Microsoft
description: A portfolio project showcasing how algorithms and data structures power the world's most visited video-sharing platform.
show_downloads: false
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
